import { ContentItem } from './types';

// Mock news recommendations for when the API is not available
export const mockNewsRecommendations: { [category: string]: ContentItem[] } = {
  tech: [
    {
      id: 'mock-tech-1',
      category: 'tech',
      title: 'The Future of Artificial Intelligence in Healthcare',
      description: 'Exploring how AI is revolutionizing medical diagnoses and treatment plans.',
      imageUrl: 'https://placehold.co/600x400/0ea5e9/ffffff?text=AI+Healthcare',
      author: 'TechNews',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about AI in healthcare...',
    },
    {
      id: 'mock-tech-2',
      category: 'tech',
      title: 'Quantum Computing Breakthrough: New Milestone Achieved',
      description: 'Scientists achieve a new breakthrough in quantum computing that could change everything.',
      imageUrl: 'https://placehold.co/600x400/8b5cf6/ffffff?text=Quantum+Computing',
      author: 'Science Daily',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about quantum computing...',
    },
    {
      id: 'mock-tech-3',
      category: 'tech',
      title: 'Revolutionary Battery Technology Could Power Electric Cars for 1000 Miles',
      description: 'New battery chemistry promises to solve range anxiety for electric vehicle owners.',
      imageUrl: 'https://placehold.co/600x400/10b981/ffffff?text=Battery+Tech',
      author: 'Green Tech',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about battery technology...',
    },
  ],
  business: [
    {
      id: 'mock-business-1',
      category: 'business',
      title: 'Tech Giants Report Record Q4 Earnings Despite Market Volatility',
      description: 'Major technology companies show resilience in challenging economic conditions.',
      imageUrl: 'https://placehold.co/600x400/f59e0b/ffffff?text=Tech+Earnings',
      author: 'Business Wire',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about tech earnings...',
    },
    {
      id: 'mock-business-2',
      category: 'business',
      title: 'Remote Work Revolution: How Companies Are Adapting to Hybrid Models',
      description: 'Analysis of how businesses are restructuring for the future of work.',
      imageUrl: 'https://placehold.co/600x400/ef4444/ffffff?text=Remote+Work',
      author: 'Work Today',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about remote work...',
    },
    {
      id: 'mock-business-3',
      category: 'business',
      title: 'Cryptocurrency Market Shows Signs of Recovery After Regulatory Clarity',
      description: 'New regulations provide framework for digital asset growth and adoption.',
      imageUrl: 'https://placehold.co/600x400/6366f1/ffffff?text=Crypto+Market',
      author: 'Crypto News',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about cryptocurrency...',
    },
  ],
  science: [
    {
      id: 'mock-science-1',
      category: 'science',
      title: 'NASA Discovers Water Ice on Mars Could Support Human Life',
      description: 'Latest Mars rover findings reveal significant water deposits beneath the surface.',
      imageUrl: 'https://placehold.co/600x400/dc2626/ffffff?text=Mars+Discovery',
      author: 'NASA News',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about Mars discovery...',
    },
    {
      id: 'mock-science-2',
      category: 'science',
      title: 'Gene Therapy Breakthrough Offers Hope for Rare Diseases',
      description: 'New treatment method shows promise in clinical trials for genetic disorders.',
      imageUrl: 'https://placehold.co/600x400/059669/ffffff?text=Gene+Therapy',
      author: 'Medical Journal',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about gene therapy...',
    },
  ],
  general: [
    {
      id: 'mock-general-1',
      category: 'general',
      title: 'Climate Scientists Warn of Accelerating Changes in Global Weather Patterns',
      description: 'New research reveals faster-than-expected shifts in climate systems worldwide.',
      imageUrl: 'https://placehold.co/600x400/16a34a/ffffff?text=Climate+Change',
      author: 'Environmental News',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about climate change...',
    },
    {
      id: 'mock-general-2',
      category: 'general',
      title: 'Global Education Initiative Aims to Bridge Digital Divide',
      description: 'International program provides technology access to underserved communities.',
      imageUrl: 'https://placehold.co/600x400/7c3aed/ffffff?text=Digital+Education',
      author: 'Global News',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about digital education...',
    },
  ],
  entertainment: [
    {
      id: 'mock-entertainment-1',
      category: 'entertainment',
      title: 'Streaming Wars Heat Up as New Platform Enters Market',
      description: 'Competition intensifies with launch of innovative entertainment service.',
      imageUrl: 'https://placehold.co/600x400/ec4899/ffffff?text=Streaming+Wars',
      author: 'Entertainment Weekly',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about streaming services...',
    },
  ],
  health: [
    {
      id: 'mock-health-1',
      category: 'health',
      title: 'Revolutionary Cancer Treatment Shows 95% Success Rate in Trials',
      description: 'New immunotherapy approach offers hope for previously untreatable cancers.',
      imageUrl: 'https://placehold.co/600x400/f97316/ffffff?text=Cancer+Treatment',
      author: 'Health News',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about cancer treatment...',
    },
  ],
  sports: [
    {
      id: 'mock-sports-1',
      category: 'sports',
      title: 'Olympic Records Shattered in Swimming Championships',
      description: 'Athletes break multiple world records in international competition.',
      imageUrl: 'https://placehold.co/600x400/0891b2/ffffff?text=Olympic+Records',
      author: 'Sports Network',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about Olympic records...',
    },
  ],
  finance: [
    {
      id: 'mock-finance-1',
      category: 'finance',
      title: 'Central Banks Consider Digital Currency Implementation',
      description: 'Major economies explore benefits of central bank digital currencies.',
      imageUrl: 'https://placehold.co/600x400/65a30d/ffffff?text=Digital+Currency',
      author: 'Financial Times',
      authorImageUrl: 'https://placehold.co/40x40.png',
      trending: false,
      link: '#',
      publishedAt: new Date().toISOString(),
      content: 'Mock article content about digital currency...',
    },
  ],
};
