
import type { ContentItem } from './types';

export const mockData: ContentItem[] = [
  {
    id: 'tech-1',
    category: 'tech',
    title: 'AI Revolutionizes Software Development',
    description: 'A new AI-powered tool can now write, test, and debug code, promising to accelerate development cycles.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'technology code',
    author: 'Dev World',
    authorImageUrl: 'https://placehold.co/40x40.png',
    trending: true,
    link: '#',
  },
  {
    id: 'finance-1',
    category: 'finance',
    title: 'Global Markets Surge on Positive Economic Outlook',
    description: 'Stocks soared today after a report showed stronger-than-expected economic growth and easing inflation.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'finance stocks',
    author: 'Market Watch',
    authorImageUrl: 'https://placehold.co/40x40.png',
    trending: true,
    link: '#',
  },
  {
    id: 'sports-1',
    category: 'sports',
    title: 'Underdogs Clinch Championship in Stunning Upset',
    description: 'The final match ended in a dramatic victory, marking one of the biggest upsets in the league\'s history.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sports trophy',
    author: 'Sports Central',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'tech-2',
    category: 'tech',
    title: 'The Future of Quantum Computing is Here',
    description: 'Researchers have unveiled a new quantum processor that solves complex problems in seconds.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'quantum computer',
    author: 'Future Tech',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'finance-2',
    category: 'finance',
    title: 'Central Bank Announces Interest Rate Hike',
    description: 'The move is aimed at curbing inflation, but raises concerns about a potential economic slowdown.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'economy bank',
    author: 'Economic Times',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'sports-2',
    category: 'sports',
    title: 'Athlete Smashes World Record in 100m Sprint',
    description: 'A new world record was set today, leaving spectators and commentators in awe of the performance.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'running race',
    author: 'The Finish Line',
    authorImageUrl: 'https://placehold.co/40x40.png',
    trending: true,
    link: '#',
  },
    {
    id: 'tech-3',
    category: 'tech',
    title: 'Cybersecurity Firm Warns of New Global Threat',
    description: 'A sophisticated malware is targeting critical infrastructure, prompting a worldwide alert.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'cyber security',
    author: 'SecureNet',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'finance-3',
    category: 'finance',
    title: 'The Rise of Digital Currencies in Emerging Markets',
    description: 'Developing nations are increasingly adopting cryptocurrencies for daily transactions.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'cryptocurrency digital',
    author: 'Crypto Journal',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'sports-3',
    category: 'sports',
    title: 'Legendary Quarterback Announces Retirement',
    description: 'After a storied 20-year career, the football icon is hanging up his helmet for good.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'american football',
    author: 'Gridiron Gazette',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'tech-4',
    category: 'tech',
    title: 'New Augmented Reality Glasses Go Mainstream',
    description: 'A sleek and affordable pair of AR glasses is set to bring augmented reality to the masses.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'augmented reality',
    author: 'Gadget Guru',
    authorImageUrl: 'https://placehold.co/40x40.png',
    trending: true,
    link: '#',
  },
  {
    id: 'finance-4',
    category: 'finance',
    title: 'Understanding the Impact of Supply Chain Disruptions',
    description: 'Experts analyze how global supply chain issues are affecting consumer prices and corporate profits.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'supply chain',
    author: 'Global Trade',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'sports-4',
    category: 'sports',
    title: 'Esports Tournament Sells Out Massive Arena',
    description: 'The global finals of the popular online game attracted tens of thousands of fans.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'esports gaming',
    author: 'Game On',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  }
];
