import type { ContentItem } from './types';

export const mockData: ContentItem[] = [
  {
    id: 'news-1',
    category: 'news',
    title: 'Tech Giants Announce Breakthrough in AI',
    description: 'A revolutionary new AI model promises to change the way we interact with technology.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'technology future',
    author: 'Tech Today',
    authorImageUrl: 'https://placehold.co/40x40.png',
    trending: true,
    link: '#',
  },
  {
    id: 'movies-1',
    category: 'movies',
    title: 'Galaxy Runners: A New Hope',
    description: 'The most anticipated sci-fi epic of the decade hits theaters this Friday.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'movie poster',
    author: 'Cinema Weekly',
    authorImageUrl: 'https://placehold.co/40x40.png',
    trending: true,
    link: '#',
  },
  {
    id: 'music-1',
    category: 'music',
    title: 'New Album "Starlight" by Aurora Drops',
    description: 'The pop sensation releases her third studio album, a blend of synth-pop and ballads.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'album cover',
    author: 'Music Hub',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'social-1',
    category: 'social',
    title: 'Viral Dance Challenge Takes Over the Internet',
    description: 'A new dance craze is sweeping social media, with millions participating worldwide.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'social media',
    author: 'Social Buzz',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'news-2',
    category: 'news',
    title: 'Global Markets React to Economic Summit',
    description: 'World leaders gathered to discuss the future of the global economy, causing a stir in the markets.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'finance economy',
    author: 'Finance World',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'movies-2',
    category: 'movies',
    title: 'Review: "The Last Laugh," a Comedy Masterpiece',
    description: 'Critics are hailing this new comedy as the funniest film of the year.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'comedy film',
    author: 'Reel Reviews',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
    {
    id: 'music-2',
    category: 'music',
    title: 'Indie Band "The Wanderers" on Their Rise to Fame',
    description: 'An exclusive interview with the breakout band of the year.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'music band',
    author: 'Indie Wave',
    authorImageUrl: 'https://placehold.co/40x40.png',
    trending: true,
    link: '#',
  },
  {
    id: 'social-2',
    category: 'social',
    title: 'Top 10 Travel Destinations for this Summer',
    description: 'Influencers share their favorite spots for an unforgettable summer vacation.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'travel vacation',
    author: 'Wanderlust',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'news-3',
    category: 'news',
    title: 'Breakthrough in Renewable Energy Storage',
    description: 'Scientists have developed a new battery technology that could revolutionize the green energy sector.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'renewable energy',
    author: 'Eco News',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'movies-3',
    category: 'movies',
    title: 'Behind the Scenes of "Chronicles of Time"',
    description: 'A look at the stunning visual effects of the fantasy blockbuster.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'fantasy movie',
    author: 'VFX Magazine',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'music-3',
    category: 'music',
    title: 'Classical Music Finds a New Audience Online',
    description: 'How streaming platforms are reviving interest in classical compositions.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'classical music',
    author: 'The Score',
    authorImageUrl: 'https://placehold.co/40x40.png',
    link: '#',
  },
  {
    id: 'social-3',
    category: 'social',
    title: 'The Rise of AI-Generated Art',
    description: 'Artists and developers are collaborating to create stunning new forms of digital art.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'digital art',
    author: 'Art & Tech',
    authorImageUrl: 'https://placehold.co/40x40.png',
    trending: true,
    link: '#',
  }
];
